```{r}
library(readxl)
library(tidyverse)
library(ggthemes)

# Reading in data from the federal reserve cutting out the top portion of the excel sheet which is just descriptions 
df <- read_excel("data/unemployment_by_educ.xls", range = "A12:C385")
```


```{r}
# Renaming the columns in the dataframe to be more descriptive 
df <- df %>% rename('BA or More' = LNS14027662, 'HS' = LNS14027660)
```


```{r}
#pivoting the df longer 
dfL <- df %>% pivot_longer(!observation_date, names_to= "Education", values_to= "Unemployment_Rate") %>%
  rename(Date = observation_date)

#extracting the year from the date variable to make plotting by year a little easier 
dfL$year <- format(dfL$Date, "%Y")
dfL$year <- as.numeric(dfL$year)
```


```{r}
# Condensing our df above grouping by year based on education level
graph <- dfL %>% group_by(year, Education) %>%
  summarise(UR_by_year = mean(Unemployment_Rate))
```


```{r}
graph %>% ggplot(aes(x = year, y = UR_by_year, color=Education)) + 
  geom_line(size = 1) +
  
  labs(title = "Average Yearly Unemployment by Education Level",
       x = "Year",
       y = "Unemployment Rate (%)") +
  
  # Modifying the x axis to look at specifc years and set the interval 
  scale_x_continuous(
    breaks = seq(1992, 2023, by=5)) +
    
  theme_clean()
```


```{r}
# Saving the graph 

#ggsave(one, filename = "graph/Unemployment_Rate.png", width = 10, height = 6)
```

